title: Chris Benz # The title of the blog
author: Chris Benz # Your name 
email: cpbenz@protonmail.com # your email shown in the footer
url: https://chrisbenz.github.io/ # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://media-exp1.licdn.com/dms/image/C5603AQEpnDsjjNFymA/profile-displayphoto-shrink_200_200/0?e=1603929600&v=beta&t=wwIfN_TtL9hoAWcXBhAKgpUNoj6_zO28_U2IDNMDAys" # avatar in about page
  about_you: Software Engineer, Security Researcher # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github: chrisbenz
    linkedin: chris-benz
    # rss: RSS
    # dribbble: 
    # flickr:   
    # instagram: 
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
